services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourPassword123! -Q \"SELECT 1\" -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: db-init
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./db.sql:/db.sql:ro
    command: >
      /bin/bash -c "
      echo 'Running DB init...' &&
      /opt/mssql-tools/bin/sqlcmd -S database -U sa -P YourPassword123! -i /db.sql &&
      echo 'DB init done.'
      "
    restart: "no"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      JWT_SECRET: mysecretkey
      DB_HOST: database
      DB_USER: sa
      DB_PASSWORD: YourPassword123!
      DB_NAME: Cars
    depends_on:
      - database
      - db-init
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mssql_data:
