version: "3.8"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123!"

    ports:
      - "1433:1433"

    volumes:
      - mssql_data:/var/opt/mssql
      - ./db.sql:/tmp/db.sql

    user: root

    command: >
      /bin/bash -c "
      apt-get update &&
      apt-get install -y curl apt-transport-https gnupg zip wget unzip &&
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft.gpg &&
      echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/20.04/prod focal main'
        > /etc/apt/sources.list.d/mssql-release.list &&
      apt-get update &&
      ACCEPT_EULA=Y apt-get install -y mssql-tools &&
      chown -R mssql:mssql /var/opt/mssql &&
      /opt/mssql/bin/sqlservr &

      echo 'Waiting for SQL Server...' &&
      sleep 30 &&

      RETRY_COUNT=0 &&
      until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123! -i /tmp/db.sql; do
        RETRY_COUNT=$((RETRY_COUNT + 1)) &&
        echo 'SQL script failed. Retrying in 20 seconds...' &&
        sleep 20 &&
        if [ $RETRY_COUNT -ge 5 ]; then
          echo 'SQL script failed after 5 attempts. Exiting.' &&
          exit 1
        fi
      done &&

      wait
      "

    #  HEALTHCHECK - Docker checks if SQL is really ready
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123! -Q \"SELECT 1\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend

    ports:
      - "5000:5000"

    environment:
      JWT_SECRET: mysecretkey
      DB_HOST: database
      DB_USER: sa
      DB_PASSWORD: YourPassword123!
      DB_NAME: Cars

    #  Backend waits until DB is healthy
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

volumes:
  mssql_data:
